# Generated by Django 4.1 on 2022-10-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('today_buy', models.IntegerField()),
                ('month_buy', models.IntegerField()),
                ('total_buy', models.IntegerField()),
            ],
        ),
    ]
