# Generated by Django 4.1 on 2022-10-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.IntegerField()),
                ('icon', models.CharField(max_length=128)),
                ('color', models.CharField(max_length=128)),
            ],
        ),
    ]
