# Generated by Django 4.1 on 2022-10-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('admin', 'admin'), ('common_user', 'common_user')], max_length=128)),
                ('menus', models.TextField()),
            ],
        ),
    ]
